# Default config: https://alacritty.org/config-alacritty.html

[general]
live_config_reload = true

[font]
size = 18.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"
dynamic_padding = false
# opacity = 0.85 # Default: 1.0
# blur = true
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"

[window.padding]
x = 12
y = 12

[colors.primary]
background = "#282c34" # Default: "#181818"
