[tools]
bun = "latest"
deno = "latest"
docker-cli = "29.7.0"
"github:gowtham-sai-yadav/entangle" = "latest"
node = "24"
"npm:aws-cdk" = "latest"
"npm:aws-cdk-local" = "latest"
"npm:npm-check-updates" = "latest"
"npm:tsx" = "latest"
"npm:typescript" = "latest"
pnpm = "latest"
python = "3.14.7"
tree-sitter = "latest"
